name: Github Pages

on:
    workflow_dispatch:
    push:
      paths-ignore:
        - '**/*'
        - '!.github/workflows/docfx.yml'
        - '!docs/docfx_project/**'
        - '!src/**/*.csproj'
        - '!src/**/*.cs'
      branches:
        - 'main' 

jobs:
    publish-docs:
      if: github.ref == 'refs/heads/main' && github.repository == 'christianhelle/refitter'
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v6  
      - run: dotnet tool update -g docfx
      - run: docfx docs/docfx_project/docfx.json  
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT }}
          external_repository: refitter/refitter.github.io
          publish_dir: docs/docfx_project/_site
          publish_branch: main
  