name: Run Tests (URL)

on:
  workflow_call:
    inputs:
      openapi:
        required: true
        type: string
      os:
        type: string
        default: ubuntu-latest
      command:
        required: true
        type: string

jobs:
  
  test:

    name: ${{ inputs.openapi }}.${{ inputs.format }} (${{ inputs.version }}) ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 5

    steps:
    - name: ğŸ›’ Checkout repository
      uses: actions/checkout@v6

    - name: ğŸ› ï¸ Generate code
      run: |        
        ${{ inputs.command }} "${{ inputs.openapi }}" --namespace "Petstore" --output Output.cs --no-logging
        ${{ inputs.command }} "${{ inputs.openapi }}" --namespace "Petstore.Interface" --output IOutput.cs --interface-only --no-logging
        ${{ inputs.command }} "${{ inputs.openapi }}" --namespace "Petstore.UsingApiResponse" --output IApiOutput.cs --interface-only --return-api-response --no-logging
        
        Copy-Item Output.cs ./ConsoleApp/Net6/
        Copy-Item Output.cs ./ConsoleApp/Net7/
        Copy-Item Output.cs ./ConsoleApp/Net8/
        Copy-Item Output.cs ./ConsoleApp/Net48/
        Copy-Item Output.cs ./ConsoleApp/Net472/
        Copy-Item Output.cs ./ConsoleApp/Net462/
        Copy-Item Output.cs ./ConsoleApp/Net481/
        Copy-Item Output.cs ./ConsoleApp/NetStandard20/
        Copy-Item Output.cs ./ConsoleApp/NetStandard21/

        Write-Host "Generated file:"
        Get-Content Output.cs | Write-Host
      working-directory: test
      shell: pwsh

    - name: ğŸ› ï¸ Build .NET 6 generated code
      run: dotnet build ./ConsoleApp/Net6/Net6.csproj
      working-directory: test

    - name: ğŸ› ï¸ Build .NET 7 generated code
      run: dotnet build ./ConsoleApp/Net7/Net7.csproj
      working-directory: test

    - name: ğŸ› ï¸ Build .NET 8 generated code
      run: dotnet build ./ConsoleApp/Net8/Net8.csproj
      working-directory: test

    - name: ğŸ› ï¸ Build .NET 4.8.1 generated code
      run: dotnet build ./ConsoleApp/Net481/Net481.csproj
      working-directory: test

    - name: ğŸ› ï¸ Build .NET 4.8 generated code
      run: dotnet build ./ConsoleApp/Net48/Net48.csproj
      working-directory: test

    - name: ğŸ› ï¸ Build .NET 4.7.2 generated code
      run: dotnet build ./ConsoleApp/Net472/Net472.csproj
      working-directory: test

    - name: ğŸ› ï¸ Build .NET 4.6.2 generated code
      run: dotnet build ./ConsoleApp/Net462/Net462.csproj
      working-directory: test

    - name: ğŸ› ï¸ Build .NET Standard 2.0 generated code
      run: dotnet build ./ConsoleApp/NetStandard20/NetStandard20.csproj
      working-directory: test

    - name: ğŸ› ï¸ Build .NET Standard 2.1 generated code
      run: dotnet build ./ConsoleApp/NetStandard21/NetStandard21.csproj
      working-directory: test
